
obj-$(CONFIG_CLKDEV_LOOKUP)		+= clkdev.o
obj-$(CONFIG_USE_COMMON_STRUCT_CLK)	+= clk.o
obj-$(CONFIG_CLK_DEBUG)			+= clk-debug.o
obj-$(CONFIG_USE_COMMON_CLK_DIVIDER)	+= clk-divider.o
obj-$(CONFIG_USE_COMMON_FACTOR_FIXED)	+= clk-fixed-factor.o
obj-$(CONFIG_USE_COMMON_CLK_MUX)	+= clk-mux.o
obj-$(CONFIG_USE_COMMON_FACTOR_FIXED)	+= clk-fixed-factor.o
obj-$(CONFIG_USE_COMMON_CLK_GATE)	+= clk-gate.o
