obj-$(CONFIG_FB_MXC_TVOUT_TVE)	+= tve.o
obj-$(CONFIG_FB_MXC_SII902X)	+= mxcfb_sii902x.o
obj-$(CONFIG_FB_MXC_LDB)	+= ldb.o
obj-$(CONFIG_FB_MODE_HELPERS)	+= mxc_edid.o
obj-$(CONFIG_FB_MXC_SYNC_PANEL)	+= mxc_dispdrv.o mxc_lcdif.o mxc_ipuv3_fb.o
